import { Coordinate } from "../shared/util";

export const SERVER_URL = `${PROTOCOL}://${HOST || "localhost"}${
    PORT ? `:${PORT}` : ""
}`;
export const MAX_ASTEROID_SPEED = 15;
export const MAX_ASTEROID_HEIGHT = 100;

export const SRC_EXPLOSION_WIDTH = 128;
export const HALF_EXPLOSION_WIDTH = SRC_EXPLOSION_WIDTH / 2;
export const EXPLOSION_LOCATIONS: Coordinate[] = [
    [0, 0],
    [SRC_EXPLOSION_WIDTH, 0],
    [2 * SRC_EXPLOSION_WIDTH, 0],
    [3 * SRC_EXPLOSION_WIDTH, 0],
    [0, SRC_EXPLOSION_WIDTH],
    [SRC_EXPLOSION_WIDTH, SRC_EXPLOSION_WIDTH],
    [2 * SRC_EXPLOSION_WIDTH, SRC_EXPLOSION_WIDTH],
    [3 * SRC_EXPLOSION_WIDTH, SRC_EXPLOSION_WIDTH],
    [0, 2 * SRC_EXPLOSION_WIDTH],
    [SRC_EXPLOSION_WIDTH, 2 * SRC_EXPLOSION_WIDTH],
    [2 * SRC_EXPLOSION_WIDTH, 2 * SRC_EXPLOSION_WIDTH],
    [3 * SRC_EXPLOSION_WIDTH, 2 * SRC_EXPLOSION_WIDTH],
    [0, 3 * SRC_EXPLOSION_WIDTH],
    [SRC_EXPLOSION_WIDTH, 3 * SRC_EXPLOSION_WIDTH],
];
